# Generated by Django 4.2.7 on 2024-01-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_taskdb_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdb',
            name='Employee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
