# Generated by Django 4.2.7 on 2024-01-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_taskdb_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Employee', models.CharField(blank=True, max_length=100, null=True)),
                ('Result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
