# Generated by Django 4.0.3 on 2024-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_reportdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdb',
            name='Due_date',
            field=models.DateField(null=True),
        ),
    ]
