# Generated by Django 4.2.7 on 2024-01-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='submissionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(blank=True, max_length=100, null=True)),
                ('Employee', models.CharField(blank=True, max_length=100, null=True)),
                ('Entry', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
